variant-calls:
  dummy-giab:
    path: "resources/variants/na12878/all.truth.bcf"
    benchmark: "giab-na12878-exome"
    genome-build: grch38
    rename-contigs: false
  dummy-chm: 
    path: "resources/variants/chm-eval/all.truth.bcf"
    benchmark: "chm-eval"
    genome-build: grch38
    rename-contigs: false
  dummy-imgag:
    path: "resources/variants/na12878-somatic/all.truth.bcf"
    benchmark: "imgag-5"
    tumor_sample_name: "HG001"
    genome-build: grch38
    rename-contigs: false
  dummy-seqc2:
    path: "resources/variants/seqc2-somatic/all.truth.format-added.vcf.gz"
    benchmark: "seqc2-wes"
    tumor_sample_name: "truth"
    vaf-field: 
      field: INFO
      name: TVAF
    genome-build: grch38
    rename-contigs: false

custom-benchmarks:
  my-custom-benchmark: # custom benchmark name, choose freely (no whitespace allowed)
    # Truth genome to consider (for now only NA12878 allowed, TODO: CHM)
    genome: na12878
    fastqs:
      - path/to/1.fq
      - path/to/2.fq
    target-regions: path/to/regions.bed
    # given target regions are on grch38 or grch37
    genome-build: grch38

limit-reads: true

reference-genome: grch38
